In [19]:
import numpy as np

np.random.seed(0)

# исходные параметры распределений двух классов
r1 = 0.7
D1 = 1.0
mean1 = [1, -2]
V1 = [[D1, D1 * r1], [D1 * r1, D1]]

r2 = 0.5
D2 = 2.0
mean2 = [1, 3]
V2 = [[D2, D2 * r2], [D2 * r2, D2]]

# моделирование обучающей выборки
N = 1000
x1 = np.random.multivariate_normal(mean1, V1, N).T
x2 = np.random.multivariate_normal(mean2, V2, N).T

# обучающая выборка для байесовского классификатора (стандартный формат)
x_train = np.hstack([x1, x2]).T
y_train = np.hstack([np.ones(N) * -1, np.ones(N)])

# вычисление оценок математических ожиданий
mm1 = np.mean(x1.T, axis=0)
mm2 = np.mean(x2.T, axis=0)

# вычисление ковариационных матриц
'''
Cov(X, Y) = matexp((X-mathexp(X)) * (Y - mathexp(Y)))
'''
a = (x1.T - mm1).T
VV1 = np.array([[np.dot(a[0], a[0]) / N, np.dot(a[0], a[1]) / N],
                [np.dot(a[1], a[0]) / N, np.dot(a[1], a[1]) / N]])

a = (x2.T - mm2).T
VV2 = np.array([[np.dot(a[0], a[0]) / N, np.dot(a[0], a[1]) / N],
                [np.dot(a[1], a[0]) / N, np.dot(a[1], a[1]) / N]])

# параметры для гауссовского байесовского классификатора
Py1, L1 = 0.5, 1  # вероятности появления классов
Py2, L2 = 1 - Py1, 1  # и величины штрафов неверной классификации

# здесь продолжайте программу
func = lambda x, cv, m, lm, py: np.log(lm * py) - 0.5 * (x - m).T @ np.linalg.inv(cv) @ (x - m) - 1/2 * np.log(np.linalg.det(cv))
predict = []
classes = [-1, 1]
for x in x_train:
    # classifier
    ind = np.argmax([func(x, VV1, mm1, L1, Py1), func(x, VV2, mm2, L2, Py2)])
    predict = np.append(predict, classes[ind])

Q = np.sum(predict != y_train)
print(Q)

4


In [ ]:
import numpy as np

np.random.seed(0)

# исходные параметры распределений двух классов
r1 = 0.7
D1 = 1.0
mean1 = [-1, -2, -1]
V1 = [[D1, D1 * r1, D1*r1*r1], [D1 * r1, D1, D1*r1], [D1*r1*r1, D1*r1, D1]]

r2 = 0.5
D2 = 2.0
mean2 = [1, 2, 1]
V2 = [[D2, D2 * r2, D2*r2*r2], [D2 * r2, D2, D2*r2], [D2*r2*r2, D2*r2, D2]]

# моделирование обучающей выборки
N = 1000
# точки в трехмерном пространстве (N штук)
x1 = np.random.multivariate_normal(mean1, V1, N).T 
x2 = np.random.multivariate_normal(mean2, V2, N).T

x_train = np.hstack([x1, x2]).T
y_train = np.hstack([np.ones(N) * -1, np.ones(N)])

# math expectation
mm1 = np.mean(x1.T, axis=0) # same mm1 = np.mean(x1, axis=1)
mm2 = np.mean(x2.T, axis=0)

a = (x1.T - mm1).T
Cv1 = np.array([[np.dot(a[0], a[0]) / N, np.dot(a[0], a[1]) / N, np.dot(a[0], a[2]) / N],
              [np.dot(a[1], a[0]) / N, np.dot(a[1], a[1]) / N, np.dot(a[1], a[2]) / N],
              [np.dot(a[2], a[0]) / N, np.dot(a[2], a[1]) / N, np.dot(a[2], a[2]) / N]])

a = (x2.T - mm2).T
Cv2 = np.array([[np.dot(a[0], a[0]) / N, np.dot(a[0], a[1]) / N, np.dot(a[0], a[2]) / N],
              [np.dot(a[1], a[0]) / N, np.dot(a[1], a[1]) / N, np.dot(a[1], a[2]) / N],
              [np.dot(a[2], a[0]) / N, np.dot(a[2], a[1]) / N, np.dot(a[2], a[2]) / N]])

Py1, L1 = 0.5, 1  # вероятности появления классов
Py2, L2 = 1 - Py1, 1  # и величины штрафов неверной классификации

func = lambda x, cv, m, lm, py: np.log(lm * py) - 1/2 * (x - m).T @ np.linalg.inv(cv) @ (x - m) - 1/2 * np.log(np.linalg.det(cv))
classes = [-1, 1]
predict = np.array([])
for x in x_train:
    ind = np.argmax([func(x, Cv1, mm1, L1, Py1), func(x, Cv2, mm2, L2, Py2)])
    predict = np.append(predict, classes[ind])

Q = np.sum(predict != y_train)
print(Q)

78


In [26]:
print(x_train)

[[-2.07377476 -4.00199662 -2.47791373]
 [-2.13689067 -3.71335797 -4.02303178]
 [-1.89394394 -2.84268827 -1.74108065]
 ...
 [ 1.83540402  2.58856921 -0.49378931]
 [ 0.41639239  2.25963214  2.72141234]
 [ 2.01767818  2.46559236  1.33621244]]


# 6

In [ ]:
import numpy as np

np.random.seed(0)

# исходные параметры распределений двух классов
mean1 = [1, -2]
mean2 = [1, 3]
r = 0.7
D = 2.0
V = [[D, D * r], [D * r, D]]

# моделирование обучающей выборки
N = 1000
# coordinates
x1 = np.random.multivariate_normal(mean1, V, N).T
x2 = np.random.multivariate_normal(mean2, V, N).T

x_train = np.hstack([x1, x2]).T
y_train = np.hstack([np.ones(N) * -1, np.ones(N)])

# вычисление оценок МО и ковариационной матрицы
mm1 = np.mean(x1.T, axis=0)
mm2 = np.mean(x2.T, axis=0)

# like Cov matrix is same for each classes
a = np.hstack([(x1.T - mm1).T, (x2.T - mm2).T])
VV = np.array([[np.dot(a[0], a[0]) / (2*N), np.dot(a[0], a[1]) / (2*N)],
                [np.dot(a[1], a[0]) / (2*N), np.dot(a[1], a[1]) / (2*N)]])

# здесь продолжайте программу
L = 1
Py = 0.5
predict = np.array([])
classes = [-1, 1]

func = lambda x, l, py, m, cov: np.log(l * py) - 1/2 * m.T @ np.linalg.inv(cov) @ m + x.T @ np.linalg.inv(cov) @ m

for x in x_train:
    ind = np.argmax([func(x, L, Py, mm1, VV), func(x, L, Py, mm2, VV)])
    predict = np.append(predict, classes[ind])

Q = np.sum(predict != y_train)
print(Q)

8
